"""Explicit bronze schema for ABS-EE EX-102 asset data.

Every column is a string, because bronze keeps the raw values. The tag lists were taken
from all 225 cached filings for GS 2017-GS6 and GS 2017-GS7 (78 loan-level tags, 54
property-level tags). An explicit schema pins the contract and skips a schema-inference
pass over every file. A test checks that every tag in the cached files is listed here, so
a new tag in a future filing fails loudly instead of being dropped.
"""

from pyspark.sql.types import ArrayType, StringType, StructField, StructType

LOAN_TAGS = [
    "GroupID",
    "NumberProperties",
    "NumberPropertiesSecuritization",
    "armIndexRatePercentage",
    "assetAddedIndicator",
    "assetNumber",
    "assetSubjectDemandIndicator",
    "assetSubjectDemandStatusCode",
    "assetTypeNumber",
    "balloonIndicator",
    "deferredInterestCollectedAmount",
    "deferredInterestCumulativeAmount",
    "demandResolutionDate",
    "firstLoanPaymentDueDate",
    "graceDaysAllowedNumber",
    "interestAccrualMethodCode",
    "interestOnlyIndicator",
    "interestRateSecuritizationPercentage",
    "lastModificationDate",
    "lienPositionSecuritizationCode",
    "liquidationPrepaymentCode",
    "liquidationPrepaymentDate",
    "loanStructureCode",
    "maturityDate",
    "modificationCode",
    "modifiedIndicator",
    "mostRecentMasterServicerReturnDate",
    "mostRecentSpecialServicerTransferDate",
    "negativeAmortizationDeferredInterestCapAmount",
    "negativeAmortizationIndicator",
    "nextInterestRatePercentage",
    "nonRecoverabilityIndicator",
    "originalAmortizationTermNumber",
    "originalInterestOnlyTermNumber",
    "originalInterestRatePercentage",
    "originalInterestRateTypeCode",
    "originalLoanAmount",
    "originalTermLoanNumber",
    "originationDate",
    "originatorName",
    "otherExpensesAdvancedOutstandingAmount",
    "otherInterestAdjustmentAmount",
    "otherPrincipalAdjustmentAmount",
    "paidThroughDate",
    "paymentFrequencyCode",
    "paymentStatusLoanCode",
    "paymentTypeCode",
    "periodicPrincipalAndInterestPaymentSecuritizationAmount",
    "postModificationAmortizationPeriodAmount",
    "postModificationInterestPercentage",
    "postModificationMaturityDate",
    "postModificationPaymentAmount",
    "prepaymentLockOutEndDate",
    "prepaymentPremiumIndicator",
    "prepaymentPremiumYieldMaintenanceReceivedAmount",
    "prepaymentPremiumsEndDate",
    "primaryServicerName",
    "realizedLossToTrustAmount",
    "reportPeriodBeginningScheduleLoanBalanceAmount",
    "reportPeriodEndActualBalanceAmount",
    "reportPeriodEndScheduledLoanBalanceAmount",
    "reportPeriodInterestRatePercentage",
    "reportPeriodModificationIndicator",
    "reportingPeriodBeginningDate",
    "reportingPeriodEndDate",
    "repurchaseAmount",
    "scheduledInterestAmount",
    "scheduledPrincipalAmount",
    "scheduledPrincipalBalanceSecuritizationAmount",
    "servicerTrusteeFeeRatePercentage",
    "servicingAdvanceMethodCode",
    "totalPrincipalInterestAdvancedOutstandingAmount",
    "totalScheduledPrincipalInterestDueAmount",
    "totalTaxesInsuranceAdvancesOutstandingAmount",
    "underwritingIndicator",
    "unscheduledPrincipalCollectedAmount",
    "workoutStrategyCode",
    "yieldMaintenanceEndDate",
]

PROPERTY_TAGS = [
    "DefeasedStatusCode",
    "debtServiceCoverageNetCashFlowSecuritizationPercentage",
    "debtServiceCoverageNetOperatingIncomeSecuritizationPercentage",
    "debtServiceCoverageSecuritizationCode",
    "defeasanceOptionStartDate",
    "financialsSecuritizationDate",
    "largestTenant",
    "leaseExpirationLargestTenantDate",
    "leaseExpirationSecondLargestTenantDate",
    "leaseExpirationThirdLargestTenantDate",
    "mostRecentAnnualLeaseRolloverReviewDate",
    "mostRecentDebtServiceAmount",
    "mostRecentDebtServiceCoverageCode",
    "mostRecentDebtServiceCoverageNetCashFlowpercentage",
    "mostRecentDebtServiceCoverageNetOperatingIncomePercentage",
    "mostRecentFinancialsEndDate",
    "mostRecentFinancialsStartDate",
    "mostRecentNetCashFlowAmount",
    "mostRecentNetOperatingIncomeAmount",
    "mostRecentPhysicalOccupancyPercentage",
    "mostRecentRevenueAmount",
    "mostRecentValuationAmount",
    "mostRecentValuationDate",
    "mostRecentValuationSourceCode",
    "netCashFlowFlowSecuritizationAmount",
    "netOperatingIncomeNetCashFlowCode",
    "netOperatingIncomeNetCashFlowSecuritizationCode",
    "netOperatingIncomeSecuritizationAmount",
    "netRentableSquareFeetNumber",
    "netRentableSquareFeetSecuritizationNumber",
    "operatingExpensesAmount",
    "operatingExpensesSecuritizationAmount",
    "physicalOccupancySecuritizationPercentage",
    "propertyAddress",
    "propertyCity",
    "propertyCounty",
    "propertyName",
    "propertyState",
    "propertyStatusCode",
    "propertyTypeCode",
    "propertyZip",
    "revenueSecuritizationAmount",
    "secondLargestTenant",
    "squareFeetLargestTenantNumber",
    "squareFeetSecondLargestTenantNumber",
    "squareFeetThirdLargestTenantNumber",
    "thirdLargestTenant",
    "unitsBedsRoomsNumber",
    "unitsBedsRoomsSecuritizationNumber",
    "valuationSecuritizationAmount",
    "valuationSecuritizationDate",
    "valuationSourceSecuritizationCode",
    "yearBuiltNumber",
    "yearLastRenovated",
]


def bronze_schema() -> StructType:
    """One <assets> element: scalar loan fields plus an array of <property> elements.

    property is an array because a multi-property loan can carry many of them (one 2017
    GS6 loan carries 39). The parser reads the first one, as parse_absee.py does.
    """
    prop = StructType([StructField(t, StringType(), True) for t in PROPERTY_TAGS])
    fields = [StructField(t, StringType(), True) for t in LOAN_TAGS]
    fields.append(StructField("property", ArrayType(prop), True))
    return StructType(fields)
